//! Byte-determinism of `gen_spots::generate` + `Suite::save` (standing ruling: every generated spot
//! file is byte-deterministic — fixed seed, stable key order, LF-only newlines on Windows — and the
//! committed `bench/spots/*.json` fixtures are required by tests, failing loudly when missing).

use bench::{gen_spots, suite::Suite};

const SUITES: [&str; 4] = ["river_std", "river_min", "turn_std", "turn_min"];

/// The workspace root, two levels above this crate (`crates/bench/../..`).
fn workspace_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn generate_bytes(suite: &str) -> Vec<u8> {
    let s: Suite = gen_spots::generate(suite, "r8").unwrap();
    let dir = std::env::temp_dir().join(format!("bench_det_{}_{}_{}", suite, std::process::id(), std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
    std::fs::create_dir_all(&dir).unwrap();
    let p = dir.join(format!("{suite}.json"));
    s.save(&p).unwrap();
    let bytes = std::fs::read(&p).unwrap();
    std::fs::remove_dir_all(&dir).unwrap();
    bytes
}

#[test]
fn generating_twice_into_separate_dirs_is_byte_identical() {
    for suite in SUITES {
        let a = generate_bytes(suite);
        let b = generate_bytes(suite);
        assert_eq!(a, b, "suite {suite}: two independent generations must be byte-identical");
        assert!(!a.contains(&b'\r'), "suite {suite}: generated bytes must be LF-only, no CR");
    }
}

#[test]
fn committed_fixtures_equal_a_fresh_generation() {
    for suite in SUITES {
        let fixture_path = workspace_root().join("bench").join("spots").join(format!("{suite}.json"));
        let committed = std::fs::read(&fixture_path)
            .unwrap_or_else(|e| panic!("committed fixture {} is required by this test and must be regenerated with `bench gen-spots`: {e}", fixture_path.display()));
        let fresh = generate_bytes(suite);
        assert_eq!(committed, fresh, "suite {suite}: committed bench/spots/{suite}.json is stale; regenerate with `cargo run -p bench -- gen-spots --source r8 --out bench/spots`");
    }
}
